name: onboarding_screen
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  get: ^4.6.6
  iconsax: ^0.0.8
  intl: ^0.19.0
  smooth_page_indicator: ^1.1.0
  url_launcher: ^6.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  #  ------------------------- LOCAL ASSETS --------------------------- #
  assets:
    - assets/animation/
    - assets/icon/
